locale = 'en-us'
title = 'CDSE custom scripts <3'
sectionPagesMenu = 'main'

[markup.highlight]
style = 'tokyonight-day'

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true
title = true

[taxonomies]
type = 'types'
verification = 'verifications'
default = 'default'
domain = 'domains'
data-source = 'data-sources'
resolution = 'resolutions'
